version: '3.8'
services:
  mongo1:
    image: mongo:latest
    container_name: mongo_rep_1
    ports:
      - 28017:27017
    command: mongod --replSet rs0 --bind_ip localhost,mongo_rep_1
    networks:
      - mongo-cluster

  mongo2:
    image: mongo:latest
    container_name: mongo_rep_2
    ports:
      - 28018:27017
    command: mongod --replSet rs0 --bind_ip localhost,mongo_rep_2
    networks:
      - mongo-cluster

  mongo3:
    image: mongo:latest
    container_name: mongo_rep_3
    ports:
      - 28019:27017
    command: mongod --replSet rs0 --bind_ip localhost,mongo_rep_3
    networks:
      - mongo-cluster

  setup:
    image: mongo:latest
    container_name: setup
    depends_on:
      - mongo1
      - mongo2
      - mongo3
    command: >
      bash -c "echo 'Waiting for MongoDB to start...' && sleep 10 &&
               mongosh --host mongo1 --eval '
                 rs.initiate({
                   _id: \"rs0\",
                   members: [
                     { _id: 0, host: \"mongo1:27017\" },
                     { _id: 1, host: \"mongo2:27017\" },
                     { _id: 2, host: \"mongo3:27017\" }
                   ]
                 })
               ' && echo 'Replica Set initiated' &&
               tail -f /dev/null"
    networks:
      - mongo-cluster

networks:
  mongo-cluster:
    driver: bridge
